### ISSUE TITLE
library pysqlite3 in Requirements.txt

### ISSUE THREAD

**Issue by idiazblanco** [computer-conflict/genes_visual_analytics#1]
- the library `pysqlite3-binary` seems to be exclusive for linux and makes installation fail in a mac
- maybe you could try replacing it in `Requirements.txt` by the more generic `pysqlite3` (this seemed to work for mac)

**Comment by computer-conflict** [comment]
It seems that the pysqlite3 package causes issues on some Linux distributions. I have separated the requirements for macOS and Linux systems.
